### ISSUE TITLE
用独立的域名：git.emacs-china.org

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/git#1]
现在网站放在： https://elpa.emacs-china.org/git/ ，有了子域名的话放到： https://git.emacs-china.org/ ，会更清楚一些。

@zilongshanren 等你有空的时候，能不能分配一个 `git.emacs-china.org` 域名，指向 ELPA 镜像所在的服务器？

**Comment by zilongshanren** [comment]
@xuchunyang  
Done

**Comment by xuchunyang** [comment]
@zilongshanren 谢谢

---

我不清楚如何给 `git.emacs-china.org` 生成 HTTPS 证书。你是之前是怎么给 `elpa.emacs-china.org` 生成证书的？

网上有一些介绍，但我还没时间细读，也不敢轻易尝试：
https://community.letsencrypt.org/t/best-practice-for-adding-sub-domain-certificates/7144
http://letsencrypt.readthedocs.io/en/latest/using.html#re-running-certbot

**Comment by zilongshanren** [comment]
我回去弄一下


From zilonshanren
在2017年01月14日 14:49，Chunyang Xu 写道:

@zilongshanren 谢谢

我不清楚如何给 git.emacs-china.org 生成 HTTPS 证书。你是之前是怎么给 elpa.emacs-china.org 生成证书的？

网上有一些介绍，但我还没时间细读，也不敢轻易尝试：
https://community.letsencrypt.org/t/best-practice-for-adding-sub-domain-certificates/7144
http://letsencrypt.readthedocs.io/en/latest/using.html#re-running-certbot

**Comment by zilongshanren** [comment]
@xuchunyang 

git.emacs-china.org 这个域名的 ssl 证书已经生成好，现在指向的网站是跟 elpa.emacs-china.org 一样了。

**Comment by xuchunyang** [comment]
谢谢。HTTPS 站点刚刚也改好了。
