### ISSUE TITLE
VPS 网速不快？

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/git#2]
我这里电信 20 Mbps 宽带，从 VPS 上下载速度基本上维持在 150 KB/s 以内。不知道其他人那边情况如何？是不是阿里云给的配置就比较低？@zilongshanren 

---
```
~$ wget http://git.emacs-china.org/org-mode.git/snapshot/org-mode-release_9.0.3.zip
--2017-01-14 14:51:52--  http://git.emacs-china.org/org-mode.git/snapshot/org-mode-release_9.0.3.zip
Resolving git.emacs-china.org (git.emacs-china.org)... 112.124.58.18
Connecting to git.emacs-china.org (git.emacs-china.org)|112.124.58.18|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-zip]
Saving to: ‘org-mode-release_9.0.3.zip’

org-mode-release_9.0.3.zip        [         <=>    ]   2.60M   132KB/s    in 24s     

2017-01-14 14:52:16 (111 KB/s) - ‘org-mode-release_9.0.3.zip’ saved [2727372]
```

**Comment by zilongshanren** [comment]
这台vps只有1m带宽，要是升级到20m带宽，一年要好几万




From zilonshanren
在2017年01月14日 15:09，Chunyang Xu 写道:

我这里电信 20 Mbps 宽带，从 VPS 上下载速度基本上维持在 150 KB/s 以内。不知道其他人那边情况如何？是不是阿里云给的配置就比较低？@zilongshanren

~$ wget http://git.emacs-china.org/org-mode.git/snapshot/org-mode-release_9.0.3.zip
--2017-01-14 14:51:52--  http://git.emacs-china.org/org-mode.git/snapshot/org-mode-release_9.0.3.zip
Resolving git.emacs-china.org (git.emacs-china.org)... 112.124.58.18
Connecting to git.emacs-china.org (git.emacs-china.org)|112.124.58.18|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-zip]
Saving to: ‘org-mode-release_9.0.3.zip’

org-mode-release_9.0.3.zip        [         <=>    ]   2.60M   132KB/s    in 24s     

2017-01-14 14:52:16 (111 KB/s) - ‘org-mode-release_9.0.3.zip’ saved [2727372]

**Comment by xuchunyang** [comment]
> 这台vps只有1m带宽，要是升级到20m带宽，一年要好几万

嗯。可以考虑升级到 2 M 带宽吗？1 M 应该是最低配，镜像如果速度慢的话，意义就大打折扣。

**Comment by zilongshanren** [comment]
升级不起，一年要多800块


From zilonshanren
在2017年01月14日 17:34，Chunyang Xu 写道:

这台vps只有1m带宽，要是升级到20m带宽，一年要好几万

嗯。可以考虑升级到 2 M 带宽吗？1 M 应该是最低配，镜像如果速度慢的话，意义就大打折扣。

**Comment by zilongshanren** [comment]
@xuchunyang  

我之前记错了，升级到 2M，要加 386 块，610 天。

**Comment by zilongshanren** [comment]
@xuchunyang  
目前这台 vps 做 elpa 的镜像，下载速度我觉得可以接受。如果做 git 镜像，clone 的速度估计还不如用 VPN 直接从国外的网站 clone。

**Comment by xuchunyang** [comment]
因为 elpa 上的包绝大多数都非常小，速度慢点也来不及察觉；但也有极少数包比较大，比如 Org mode

http://elpa.emacs-china.org/org/org-20161224.tar (5.74M)

```
(calc-eval "5.74 * 1024 / (1024 / 8)")
     ⇒ "45.92"
```

大概需要 46 秒，如果 VPS 是 2M 的话，可以比现在节省一半的时间，效果还是非常可观的。

**Comment by xuchunyang** [comment]
等以后有条件的时候，再考虑吧。

**Comment by zilongshanren** [comment]
@xuchunyang 

我已升级到 2M，你试试看

**Comment by xuchunyang** [comment]
嗯，应该变成 2M 了，现在从 ELPA 镜像上安装 Org Mode 的话应该比原来少二十几秒。

---
至于这个 Git 镜像，考虑到：

- 反正上游也没有被墙，而我们的镜像也不是非常快
- 会影响到 ELPA 镜像的速度

我待会儿会关闭 `git-clone` 服务。至于 https://git.emacs-china.org/ 这个网页和这个 Repo 都还会留着，我会在 README 中作出解释。

**Comment by xuchunyang** [comment]
> 我待会儿会关闭 git-clone 服务

Done
